name: Build and deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'resources/**'
      - 'package/**'
      - deps.edn

jobs:  
  build:
    runs-on: ubuntu-22.04

    # env:
    #   JVM_OPTS: -Xmx3200m

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: 1.11.1.1200
      
      - name: Package
        run: ./script/package.sh

      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: 'target/*.jar'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: grumpy.website

      - name: Deploy
        run: |
          scp target/grumpy.jar grumpy@grumpy.website:

      - name: Restart
        run: |
          ssh grumpy@grumpy.website "kill \$(systemctl show --property MainPID --value grumpy)"

