name: Build and deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'resources/**'
      - 'package/**'
      - deps.edn
      - .github/workflows/build-deploy.yml

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_21_X64/bin" >> $GITHUB_PATH

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: latest

      - name: Package
        run: ./script/package.sh

      - uses: actions/upload-artifact@v4
        with:
          name: jar
          path: 'target/*.jar'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        run: |
          scp target/grumpy.jar grumpy@grumpy.website:

      - name: Restart
        run: |
          ssh grumpy@grumpy.website "kill \$(systemctl show --property MainPID --value grumpy)"

